/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UIPackage;

/**
 *
 * @author pabas
 */
public class ManagerMainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ManagerMainFrame.class.getName());

    /**
     * Creates new form ManagerMainFrame
     */
    public ManagerMainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnManageUsers = new javax.swing.JButton();
        btnManageCashierFunction = new javax.swing.JButton();
        btnReturns = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnInventory = new javax.swing.JButton();
        btnPricing = new javax.swing.JButton();
        btnManageSuplier = new javax.swing.JButton();
        btnManageCategory = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        btnManageUsers.setBackground(new java.awt.Color(102, 102, 255));
        btnManageUsers.setText("Manage Users");
        btnManageUsers.addActionListener(this::btnManageUsersActionPerformed);

        btnManageCashierFunction.setBackground(new java.awt.Color(102, 102, 255));
        btnManageCashierFunction.setText("Manage Cashier Fuction");
        btnManageCashierFunction.addActionListener(this::btnManageCashierFunctionActionPerformed);

        btnReturns.setBackground(new java.awt.Color(102, 102, 255));
        btnReturns.setText("Returns");
        btnReturns.addActionListener(this::btnReturnsActionPerformed);

        btnLogout.setBackground(new java.awt.Color(102, 102, 255));
        btnLogout.setText("Logout");
        btnLogout.addActionListener(this::btnLogoutActionPerformed);

        btnInventory.setBackground(new java.awt.Color(102, 102, 255));
        btnInventory.setText("Inventory");
        btnInventory.addActionListener(this::btnInventoryActionPerformed);

        btnPricing.setBackground(new java.awt.Color(102, 102, 255));
        btnPricing.setText("Pricing");
        btnPricing.addActionListener(this::btnPricingActionPerformed);

        btnManageSuplier.setBackground(new java.awt.Color(102, 102, 255));
        btnManageSuplier.setText("Manage Suplier");
        btnManageSuplier.addActionListener(this::btnManageSuplierActionPerformed);

        btnManageCategory.setBackground(new java.awt.Color(102, 102, 255));
        btnManageCategory.setText("Manage Category");
        btnManageCategory.addActionListener(this::btnManageCategoryActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Manager Panel");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(121, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnManageUsers)
                            .addComponent(btnManageCashierFunction)
                            .addComponent(btnManageCategory)
                            .addComponent(btnManageSuplier))
                        .addGap(139, 139, 139)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLogout)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(btnReturns))
                            .addComponent(btnInventory)
                            .addComponent(btnPricing))
                        .addGap(82, 82, 82))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(163, 163, 163))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnManageCashierFunction)
                    .addComponent(btnReturns))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnManageUsers)
                    .addComponent(btnPricing))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnManageCategory)
                    .addComponent(btnInventory))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnManageSuplier)
                    .addComponent(btnLogout))
                .addContainerGap(129, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(133, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventoryActionPerformed
        InventoryControlFrame obj=new InventoryControlFrame();
        obj.show();
        this.dispose();
    }//GEN-LAST:event_btnInventoryActionPerformed

    private void btnManageCashierFunctionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageCashierFunctionActionPerformed
       CashierMainFrame obj=new CashierMainFrame();
        obj.show();
        this.dispose();
    }//GEN-LAST:event_btnManageCashierFunctionActionPerformed

    private void btnManageUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageUsersActionPerformed
        RegisterFrame obj=new RegisterFrame();
        obj.show();
        this.dispose();      
    }//GEN-LAST:event_btnManageUsersActionPerformed

    private void btnManageCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageCategoryActionPerformed
       ManageCategoryFrame obj=new ManageCategoryFrame();
       obj.show();
       this.dispose();
    }//GEN-LAST:event_btnManageCategoryActionPerformed

    private void btnManageSuplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageSuplierActionPerformed
         SupplierFrame obj=new SupplierFrame();
        obj.show();
        this.dispose();
                             
    }//GEN-LAST:event_btnManageSuplierActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
         LoginFrame obj=new LoginFrame();
        obj.show();
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnPricingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPricingActionPerformed
           PricingFrame obj=new PricingFrame();
            obj.show();
            this.dispose();
    }//GEN-LAST:event_btnPricingActionPerformed

    private void btnReturnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnsActionPerformed
        ReturnFrame obj=new ReturnFrame();
            obj.show();
            this.dispose();
    }//GEN-LAST:event_btnReturnsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ManagerMainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInventory;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnManageCashierFunction;
    private javax.swing.JButton btnManageCategory;
    private javax.swing.JButton btnManageSuplier;
    private javax.swing.JButton btnManageUsers;
    private javax.swing.JButton btnPricing;
    private javax.swing.JButton btnReturns;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
